services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: prod
    
    container_name: backend4${PROJECT_NAME}

    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      db:
        condition: service_healthy

    expose:
      - "8000"

  frontend:
    
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: runner
     
    container_name: frontend${PROJECT_NAME}
    
    restart: unless-stopped

    env_file:
      - .env

    expose:
      - "3000"


  db:
    
    build:
      context: ./_docker/postgis
      dockerfile: Dockerfile
    
    container_name: db4${PROJECT_NAME}
    
    env_file:
      - .env

    volumes:
      - dbdata:/var/lib/postgresql

    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    
    expose:
      - 5432

  redis:
    build:
      context: ./_docker/redis
      dockerfile: Dockerfile

    container_name: redis4${PROJECT_NAME}

    restart: unless-stopped
    
  nginx:
    build:
      context: ./_docker/nginx
      dockerfile: Dockerfile
    
    container_name: nginx4${PROJECT_NAME}

    restart: unless-stopped


    ports:
      - "80:80"

    volumes:
      - ./_docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - backend
      - frontend


volumes:
  dbdata:
    name: ${PROJECT_NAME}_dbdata_v