"""create estimate table

Revision ID: 35114b8ab4b0
Revises: 
Create Date: 2026-09-25 21:20:20.101718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '35114b8ab4b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estimates',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('geometry_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sa.Integer(), nullable=True),
    sa.Column('point', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('polygon', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('sos', sa.Date(), nullable=False),
    sa.Column('eos', sa.Date(), nullable=False),
    sa.Column('scheme_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('npp', sa.Float(), nullable=True),
    sa.Column('eyield_tpha', sa.Float(), nullable=True),
    sa.Column('aeti_mm', sa.Float(), nullable=True),
    sa.Column('wp_kgpm3', sa.Float(), nullable=True),
    sa.Column('lgp', sa.Float(), nullable=True),
    sa.Column('area_ha', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estimates')
    # ### end Alembic commands ###
